mapping dictionary = 
  ([
     "apology": "appy polly loggy",
     "bad": "baddiwad",
     "band": "banda",
     "battle": "bitva",
     "bastard": "bratchny",
     "belly": "brooko",
     "big": "bolshy",
     "boy": "malchick",
     "brother": "bratty",
     "chaplain": "charlie",
     "cigarette": "cancer",
     "cup": "chasha",
     "feces": "cal",
     "fellow": "chelloveck",
     "god": "bog",
     "great": "bolshy",
     "guard": "chasso",
     "library": "biblio",
     "mad": "bezoomny",
     "man": "chelloveck",
     "nonsense": "chepooka",
     "office": "cantora",
     "old woman": "baboochka",
     "person": "chelloveck",
     "pocket": "carman",
     "razor": "britva",
     "rich": "bugatty",
     "shit": "cal",
     "sick": "bolnoy",
     "tea": "chai",
     "throw": "brosay",
     "wash": "cheest",
     "woman": "cheena",
  ]);

